### ISSUE TITLE
Multiple CSRF token

### ISSUE THREAD

**Issue by mkoumila** [kubetail-org/edge-csrf#50]
Hello @amorey  ,
I have a custom Node.js server set up with Next.js 14 in my pages route, using the package you recently created, **@edge-csrf/node-http**.

Everything works well in terms of token generation; however, I encounter an issue where each request generates a new CSRF token, different from the previous one. Consequently, when I attempt to post a request, I receive an "invalid CSRF token" error.

How can I resolve this issue to ensure the CSRF token remains consistent across requests?

this is my custom server:

`const { loadEnvConfig, processEnv } = require("@next/env");
const loadedEnvConfig = loadEnvConfig(__dirname, false);
processEnv(loadedEnvConfig.loadedEnvFiles);
process.env.NODE_ENV = "production";
process.chdir(__dirname);

const { createServer } = require("http");
const { parse } = require("url");
const next = require("next");

process.env.NODE_ENV = "development";
const dev = true;
const hostname = process.env.HOSTNAME || "localhost";
const port = parseInt(process.env.PORT, 10) || 3000;
const app = next({ dev, hostname, port });
const handle = app.getRequestHandler();

const { createCsrfProtect, CsrfError } = require("@edge-csrf/node-http");

// initalize csrf protection middleware
const csrfProtect = createCsrfProtect({
  cookie: {
    secure: true,
  },
});

app.prepare().then(() => {
  createServer(async (req, res) => {
    try {
      // apply csrf protection
      await csrfProtect(req, res);
      const parsedUrl = parse(req.url, true);
      await handle(req, res, parsedUrl);
    } catch (err) {
      if (err instanceof CsrfError) {
        res.writeHead(403);
        res.end("invalid csrf token");
        throw new Error(err);
      }
      console.error("Error occurred handling", req.url, err);
      res.statusCode = 500;
      res.end("internal server error");
    }
  })
    .once("error", (err) => {
      console.error(err);
      process.exit(1);
    })
    .listen(port, () => {
      console.log("🚀🚀🚀 Ready on localhost:3000");
    });
})`

<img width="832" alt="image" src="https://github.com/kubetail-org/edge-csrf/assets/108822271/9a53cc11-4a6c-4f21-93a6-e27946ddcc20">

**Comment by amorey** [comment]
Each request creates a new unique token generated by hashing the secret (stored in a cookie) with a random salt (see [here](https://github.com/kubetail-org/edge-csrf/blob/main/shared/src/protect.ts#L145) and [here](https://github.com/kubetail-org/edge-csrf/blob/main/shared/src/util.ts#L140)) so the token generation behavior you're seeing is expected. How are you passing the token from your node-http server to the Next.js app? Is it possible that the behavior you're seeing is because the forms being generated by the Next.js app don't include the token?

**Comment by mkoumila** [comment]
Hello @amorey ,
I'm passing the CSRF token to my form component like in this example: https://github.com/kubetail-org/edge-csrf/blob/main/examples/next14-pagesrouter-html-submission/pages/index.tsx

The problem is, the token that get passed to my webform is the old one from the previous request since i get multiple CSRF tokens from multiple requests.
For example, let's take the image from my question above, when i hit Submit in my webform, the CSRF token that passes is the one that ends with **ia09S62J** which is the old one not the new one.

**Comment by amorey** [comment]
There are no “old” tokens; any token generated by a request will work since they’re just signed hashes of the same original secret. Can you make sure that the csrf secret in the browser’s cookies isn’t changing between requests? If you can share a minimal example that demonstrates the error, I could debug the problem more easily.

**Comment by mkoumila** [comment]
Hello @amorey ,
I just created a simple example using NextJs 14, and seems like it the fetch request that has CSRF token is pending, and when i published it in Vercel, ithe CSRF token wasn't generated at all
Github repo: https://github.com/mkoumila/csrf-test
Live example: https://csrf-test-sable.vercel.app/

Thanks

**Comment by amorey** [comment]
Thanks for the example code, that helped. The issue was that edge-csrf was reading the incoming request body without passing the data along to next. Try @edge-csrf/node-http:2.2.2.

Also, I'd recommend excluding '_next' from csrf protection to avoid unnecessary cycles on static files:
```javascript
const csrfProtect = createCsrfProtect({
  excludePathPrefixes: ['/_next/'],
  cookie: {
    secure: process.env.NODE_ENV === 'production',
  },
})
```

Let me know if the new version works for you.

**Comment by mkoumila** [comment]
Works well ! 
Thanks @amorey 🙏

**Comment by amorey** [comment]
Great! Happy to hear that fixed the problem.
