### ISSUE TITLE
SECURITY ISSUE???

### ISSUE THREAD

**Issue by jspm2013** [kubetail-org/edge-csrf#56]
Hey and thanks for the Repo/Library!!

I've maybe found an issue with it -->

- very simple to reproduce, I am working with the nextjs14 app router static example (but i guess it does not matter at this point), and I am using "@edge-csrf/nextjs": "^2.2.2"

- "next": "14.2.4", react 18+ and node 20+

- whats the issue?
--->>> if I am going to add exact one single character (and it absolutely does not matter which one it is) to the very end of the csrf_token string (input/hidden) inside of a form, and then will submit it, the algorithm always accepts it as safe and valued, and passes the request forward from the middleware to the route, where I would expect the protection function to deny it and throw error.

It dos not work with two or more added chars at the end, but only with one single char attached.

Please have a check on it and give some feedback.

**Comment by amorey** [comment]
Thanks for the note! I dug into this and I don't think it's a problem. The reason why adding an extra character doesn't matter is because internally edge-csrf uses the JavaScript internal method `atob()` to decode the base64 encoded token string into a byte array and that method ignores the last character if it's not valid base64 ([see here](https://github.com/kubetail-org/edge-csrf/blob/main/shared/src/protect.ts#L139)). I don't think this is a security problem because you still need all of the other characters in the token string to be correct in order for the token to pass validation. Please feel free to look at this more closely and verify that edge-csrf still requires the other token characters to be match.

**Comment by jspm2013** [comment]
You're welcome! I thought somehow the same what you mentioned, but as I am not an expert on this topic, I would rather inform you - do you think it would make sense to let this "question" (if it might be a vulnerability in some cases, or not), answer some guys in one of the matching reddit channels? I don't want to give you miss-credit, because I really appreciate the work you did here...but I know some creators wont like it to go around with those topics.
